# Generated by Django 5.0.3 on 2025-08-23 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='galeryproduct',
            old_name='Product',
            new_name='product',
        ),
    ]
