# Generated by Django 5.0.3 on 2025-09-06 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baners', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='banerheader',
            name='link',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='banerhomepage',
            name='link',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
